language: java
sudo: false
branches:
  only:
    - master
script: 
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ant -lib lib/ant-salesforce.jar -Dsf.username=${sf.user} -Dsf.password=${sf.pass}${sf.token} deployRunNoTests || [ "${TRAVIS_PULL_REQUEST}" != "false" ]'
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && ant -lib lib/ant-salesforce.jar -Dsf.username=${sf.user} -Dsf.password=${sf.pass}${sf.token} validateAllTests || [ "${TRAVIS_PULL_REQUEST}" = "false" ]'
