language: java
sudo: false
branches:
  only:
    - master
script: 
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ant -lib lib/ant-salesforce.jar -Dsf.username=${SFUSR} -Dsf.password=${SFPASS} deployWithUnitTests || [ "${TRAVIS_PULL_REQUEST}" != "false" ]'
